---
title: "Μεθοδολογία Εκπαιδευτικής Έρευνας (0110Υ)"
subtitle: "Χειμερινό εξάμηνο 2025-2026"
author: "Αλέξανδρος Ρέκκας"
date: "2025-12-18"
format:
  revealjs:
    theme: [default, custom.scss]
    logo: logo.jpg
    footer: "Μεθοδολογία Εκπαιδευτικής Έρευνας: _11ο Μάθημα_"
    slide-number: c/t
    incremental: false
    transition: slide
    background-transition: fade
    highlight-style: monokai
    code-line-numbers: false
    preview-links: auto
    width: 1280
    height: 720
lang: el
---

# Ανακεφαλαίωση

# Έρευνα δράσης

## Γενικά

\

**Έρευνα δράσης** είναι μια συστηματική έρευνα που πραγματοποιείται από
εκπαιδευτικούς, διευθυντές, σχολικούς συμβούλους ή άλλους εμπλεκόμενους με το
περιβάλλον της διδασκαλίας.

\

**Σκοπός** είναι να προσφέρει στους εκπαιδευτικούς μια μέθοδο επίλυσης των
καθημερινών τους προβλημάτων.

\

Η έρευνα δράσης είναι η έρευνα που πραγματοποιείται από τους εκπαιδευτικούς για
τους εκπαιδευτικούς.

## Γενικά

\

Η έρευνα δράσης:

- Συμβάλλει στην ενίσχυση της επαγγελματικής ανάπτυξης των εκπαιδευτικών.
- Ωθεί τους εκπαιδευτικούς προς τη συνεχή μάθηση στις σχολικές τάξεις και στις
  πρακτικές τους.
- Προωθεί σωστά πρότυπα και στους μαθητές τόσο για τις δεξιότητες που
  απαιτούνται για τη σωστή μάθηση αλλά και για την περιέργεια και το ενδιαφέρον
  αναζήτησης νέας γνώσης.

## Γενικά

Η έρευνα δράσης:

- Ενσωματώνεται ως αναστοχαστική στάση στην καθημερινή ρουτίνα του εκαπιδευτικού.
- Συμβάλλει στην επαγγελματική στάση των εκπαιδευτικών.
- Ενθαρρύνει τους εκπαιδευτικούς: 
  - Να εξετάσουν τη δυναμική των τάξεών τους.
  - Να αναλογιστούν την αλληλεπίδραση τόσο μεταξύ αυτών και των μαθητών όσο και των μαθητών μεταξύ τους.
  - Να επικυρώσουν ή να αμφισβητήσουν πρακτικές που χρησιμοποιούν.
  
# Βασικά χαρακτηριστικά της έρευνας δράσης

## Αναγκαιότητα έρευνας δράσης

Η αναγκαιότητα της έρευνας δράσης αναδύεται από τη συχνή **αποτυχία** της
εκπαιδευτικής έρευνας να επηρεάσει τη διδασκαλία:

- Συχνά, οι εκπαιδευτικοί δε θεωρούν τις έρευνες πειστικές ή έγκυρες.
- Οι έρευνες δε σχετίζονται με την πράξη και δε σχετίζονται με τα ερωτήματα των
  εκπαιδευτικών.
- Τα ευρήματα των ερευνών δε διατυπώνονται με τρόπους κατανοητούς για τους
  εκπαιδευτικούς.
- Το ίδιο το εκπαιδευτικό σύστημα δεν είναι σε θέση να αλλάξει, ή αντίστροφα,
  είναι εκ φύσεως ασταθές και επιρρεπές σε μόδες.

## Είναι πειστική και έγκυρη

- Περιλαμβάνει πειστικά δεδομένα, αφού πραγματοποιείται από τους ίδιους τους
  εκπαιδευτικούς.
- Οι εκπαιδευτικοί επενδύουν στη νομιμότητα της συλλογής δεδομένων.
- Τα αποτελέσματα είναι έγκυρα για καθώς αναπτύσσονται λύσεις για τα πραγματικά
  προβλήματα στη διδασκαλία.
- Οι εκπαιδευτικοί και όχι μόνο οι εξωτερικοί ειδικοί γνωρίζουν τι δουλεύει και
  τι όχι μέσα στις τάξεις τους.
  
## Είναι συναφής

Η συνάφεια μεταξύ των δημοσιευμένων αποτελεσμάτων εκπαιδευτικών ερευνών και του
πραγματικού κόσμου είναι από τις πιο κοινές ανησυχίες των εκπαιδευτικών:

- Τα προβλήματα που μελετώνται μπορεί να μην είναι συναφή.
- Οι τάξεις και τα εκπαιδευτικά συστήματα που μελετώνται μπρεί να είναι
  διαφορετικά.

Η τάξη χαρακτηρίζεται από **αβεβαιότητα**.

\

Η έρευνα δράσης ενισχύει την **δυνατότητα πρόβλεψης** του/της εκπαιδευτικού.

## Είναι προσβάσιμη

\

Τα αποτελέσματα των εκπαιδευτικών ερευνών συχνά δεν βρίσκουν το "δρόμο" τους για
την τάξη επειδή:

- Δεν λαμβάνουν συχνά υπόψη τους τις πεποιθήσεις και τις αξίες των εκπαιδευτικών.
- Δεν επιτρέπουν την πρόσβαση στα ερευνητικά δεδομένα.
- Ακόμα και αν όλοι οι εκπαιδευτικοί ενημερώνονταν για τα ευρήματα ελάχιστοι θα
  ήταν σε θέση να αλλάξουν την πρακτική τους.
  
## Είναι προσβάσιμη

\

Η "ομορφιά" της έρευνας δράσης:

- Οι ερευνητές αμφισβητούν τις **δικές τους** πρακτικές.
- Τα ευρήματα έχουν νόημα καθώς σχετίζονται με την περιοχή ενδιαφέροντος του
  ίδιου του εκπαιδευτικού.
- Η διάθεση αναστοχασμού κάνει τον εκπαιδευτικό πιο παραγωγικό μέλος της
  επαγγελματικής κοινότητας.

## Προκλήσεις

Η απουσία σύνδεσης των αποτελεσμάτων της έρευνας και της εκπαιδευτικής πρακτικής
μπορεί να οφείλεται και στο ίδιο το εκπαιδευτικό σύστημα:

- Δεν υπάρχουν επαρκώς καθορισμένοι στόχοι.
- Επιρρεπές σε μόδες και συγχρόνως δυσκίνητο.
- Υιοθέτηση πολλών αταίριαστων πρακτικών.

\

Η έρευνα δράσης προσπαθεί να δώσει στους εκπαιδευτικούς τα εργαλεία για να
επιλύουν στο βαθμό που είναι δυνατό τα προβλήματα της καθημερινής εκπαιδευτικής
πρακτικής.

# Προσεγγίσεις της έρευνας δράσης

## Κριτική έρευνα δράσης

Ονομάζεται _κριτική_ διότι βασίζεται στην κριτική θεωρία και όχι γιατί είναι
επικριτική.

\

Οι αξίες της κριτικής έρευνας δράσης είναι:

- **Δημοκρατική:** επιτρέπει τη συμμετοχή όλων των ανθρώπων.
- **Δίκαιη:** Αναγνωρίζει την ισότητα.
- **Χειραφετητική:** Παρέχει ελευθερία σε καταπιεστικές καταστάσεις.
- **Βελτιώνει τη ζωή:** Επιτρέπει την έκφραση όλου του δυναμικού των ανθρώπων.

## Πρακτική έρευνα δράσης

Η **πρακτική έρευνα δράσης** επικεντρώνεται περισσότερο στην αναζήτηση λύσης
ενός πορβλήματος που εντοπίστηκε.

\

Οι βασικές παραδοχές είναι ότι οι εκπαιδευτικοί ερευνητές:

- Έχουν δυνατότητα λήψης αποφάσεων για το μάθημά τους.
- Ενδιαφέρονται για την διαρκή επαγγελματική τους εξέλιξη και τη βελτίωση του σχολείου.
- Αναζητούν τον αναστοχασμό στις πρακτικές τους.
- Θα επιλέξουν μία περιοχή εστίασης.

# Επίπεδα στην έρευνα δράσης

## Γενικά

\

Η εκπαιδευτική έρευνα δράσης μπορεί να πραγματοποιηθεί σε τρία διαφορετικά επίπεδα:

- Σε ένα μόνο νηπιαγωγείο.
- Σε επίπεδο ευρύτερου σχολικού συστήματος.
- Σε ατομικό επίπεδο.

## Σε ένα νηπιαγωγείο

\

Σε ένα μόνο νηπιαγωγείο η έρευνα δράσης μπορεί να έχει τα παρακάτω χαρακτηριστικά:

- Έρευνα δράσης από εκπαιδευτικούς πάνω σε ένα κοινό ζήτημα.
- Συνήθως, ομάδες εκπαιδευτικών με κοινά γνωστικά αντικείμενα.
- Εμπλοκή με άλλες συνεργατικές ή συμμετοχικές μορφές έρευνας, π.χ. συνεργασία
  με κάποιον ακαδημαϊκό ερευνητή.

## Σε επίπεδο ευρύτερου σχολικού συστήματος

\

Σε επίπεδο ευρύτερου σχολικού συστήματος η έρευνα δράσης μπορεί να έχει τα
παρακάτω χαρακτηριστικά:

- Η πλειονότητα των νηπιαγωγείων μιας περιφέρειας εντοπίζει ένα κοινό πρόβλημα.
- Έρευνα σε έναν εστιασμένο στόχο.
- Υπάρχει δυνατότητα δημιουργίας ερευνητικών ομάδων με μεγαλύτερο εύρος
  ειδικεύσεων, π.χ. εκπαιδευτικοί, διευθυντές, διοικητικά στελέχη, σύμβουλοι.
  
  
## Σε ατομικό επίπεδο

\

Σε ατομικό επίπεδο η εκπαιδευτική έρευνα δράσης μπορεί να πάρει έχει τα παρακάτω
χαρακτηριστικά:

- Μελέτη πτυχών της τάξης που είναι μοναδικές για τον/την εκπαιδευτικό και τους
  μαθητές του/της.
- Παρατήρηση των μαθητών στην τάξη κατά τη διάρκεια του μαθήματος.
- Κατασκευή απλών εργαλείων ή διαδικασιών για τη συλλογή πληροφοριών.

# Η διαδικασία της έρευνας δράσης

## Γενικά

\

Τα βασικά βήματα για την πραγματοποίηση μίας έρευνας δράσης είναι:

- Εντοπισμός της περιοχής εστίασης.
- Συλλογή δεδομένων.
- Ανάλυση και ερμηνεία των δεδομένων.
- Σχεδιασμός δράσης.

## Εντοπισμός της περιοχής εστίασης

Μπορεί να είναι δύσκολο ζήτημα (συχνά είναι πολλά τα ζητήματα που έχουν να
αντιμετωπίσουν)


Για την επιλογή της περιοχής εστίασης χρειάζεται να ικανοποιούνται τα ακόλουθα κριτήρια:

- Να περιλαμβάνει τη διδασκαλία και τη μάθηση και να επικεντρώνεται στην
  εκπαιδευτική πρακτική του ερευνητή.
- Να είναι κάτι που βρίσκεται στον έλεγχο του ερευνητή.
- Να είναι κάτι ενδιαφέρον.
- Να είναι κάτι που ερευνητής επιθυμεί να αλλάξει ή να βελτιώσει.

## Εντοπισμός της περιοχής εστίασης

Ακολουθεί η αποσαφήνιση:

- Απαιτεί χρόνο.
- Αναστοχασμός πεποιθήσεων.
- Κατανόηση της φύσης και της ευρύτερης ιδέας.
- Απόκτηση γνώσεων σχετικά με την ερευνητική περιοχή.

## Κατανόηση μέσω αυτο-στοχασμού

Για την αποσαφήνιση της κατάστασης συχνά απαιτείται διερεύνηση:

- Των θεωριών που επηρεάζουν την πρακτική του εκπαιδευτικού-ερευνητή.
- Των εκπαιδευτικών αξιών του εκπαιδευτικού-ερευνητή.
- Του τρόπου που η δουλειά του εκπαιδευτικού-ερευνητή εντάσσεται στο ευρύτερο
  πλαίσιο της εκπαίδευσης και της κοινωνίας.
- Το ιστορικό πλαίσιο του σχολείου και της εκπαίδευσης.
