---
title: "Μεθοδολογία Εκπαιδευτικής Έρευνας (0110Υ)"
subtitle: "Χειμερινό εξάμηνο 2025-2026"
author: "Αλέξανδρος Ρέκκας"
date: "2025-12-11"
format:
  revealjs:
    theme: [default, custom.scss]
    logo: logo.jpg
    footer: "Μεθοδολογία Εκπαιδευτικής Έρευνας: _10ο Μάθημα_"
    slide-number: c/t
    incremental: false
    transition: slide
    background-transition: fade
    highlight-style: monokai
    code-line-numbers: false
    preview-links: auto
    width: 1280
    height: 720
lang: el
---

# Μικτές μέθοδοι

## Υπενθύμιση

| Ποσοτικές μέθοδοι                                      | Ποιοτικές μέθοδοι                         |
|:-------------------------------------------------------|:------------------------------------------|
| Χρήση απαγωγικής προσέγγισης                           | Χρήση επαγωγικής προσέγγισης              |
| Αντικειμενική πραγματικότητα που πρέπει να ανακαλυφθεί | Ερμηνεία απόψεων των συμμετεχόντων        |
| Μελέτη σχέσεων αιτίου-αιτιατού                         | Περιγραφή και κατανόηση σχέσεων           |
| Διατύπωση και εξέταση υποθέσεων                        | Γενική υπόθεση που εστιάζεται στην πορεία |
| Τυχαία επιλογή συμμετεχόντων                           | Σκόπιμη επιλογή συμμετεχόντων             |

## Εισαγωγικά

Η έρευνα μικτών μεθόδων συνδυάζει ποσοτικές και ποιοτικές προσεγγίσεις.

\

Στόχος η πληρέστερη κατανόηση ενός φαινομένου σε σύγκριση με τις μεμονωμένες
προσεγγίσεις.

\

Σπάνια ένας/μία ερευνητής/τρια κατέχει επαρκείς γνώσεις, ώστε να εφαρμόσει και τις
δύο ερευνητικές προσεγγίσεις.

## Τύποι σχεδίων έρευνας μικτών μεθόδων

Οι πιο συχνοί τύποι σχεδιασμού είναι μικτών μεθόδων είναι:

* Το μοντέλο ΠΟΙΟΤ-ποσοτ (QUAL-quan)
* Το μοντέλο ΠΟΣΟΤ-ποιοτ (QUAN-qual)
* Το μοντέλο ΠΟΣΟΤ-ΠΟΙΟΤ (QUAN-QUAL)

\

Η μέθοδος που γράφεται με κεφαλαία έχει το μεγαλύτερο βάρος.  
Όταν και οι δύο μέθοδοι γράφονται με κεφαλαία, τότε είναι ισοδύναμες.

## Το μοντέλο ΠΟΙΟΤ-ποσοτ

* Ονομάζεται και _διερευνητικό σχέδιο με μικτές μεθόδους_.
* Τα ποιοτικά δεδομένα συλλέγονται πρώτα και έχουν μεγαλύτερο βάρος.

* Ποιοτικό μέρος:
  * Διερεύνηση με τη μορφή παρατηρήσεων και ανοιχτών συνεντέυξεων.
  * Ένας συμμετέχοντας ή μικρή ομάδα συμμετεχόντων.
  * Προσδιοπρίζονται έννοιες και πιθανές υποθέσεις.
* Ποσοτικό μέρος:
  * Προσδιορισμός μεταβλητών που προέκυψαν από την ποιοτική ανάλυση.
  * Έλεγχος υποθέσεων
  
## Παραδείγμα

* **Στόχος:** Να μελετηθούν οι παιδαγωγικές αλληλεπιδράσεις μεταξύ δασκάλων και μαθητών.
* Βιντεοσκόπηση μαθήματος σε νηπιαγωγεία.
* Ερωτηματολόγια σε δασκάλους.
* Συνεντεύξεις με συμμετέχοντες δασκάλους.
* Μετατροπή (κωδικοποίηση) όσων συμβαίνουν στα βίντεο (π.χ. "making reasoning explicit")
* Στατιστική ανάλυση των κωδικοποιημένων στοιχείων.

## Παράδειγμα

Ερευνητικά ερωτήματα:

* Πώς τα δημοτικά σχολεία εντάσσουν τη φυσική δραστηριότητα στην καθημερινότητα
  των παιδιών, πέρα από το τυπικό μάθημα της Φυσικής Αγωγής;
* Χρησιμοποιούν οι δάσκαλοι "διαλείμματα κίνησης" (brain breaks) μέσα στην τάξη;
* Υπάρχουν προγράμματα περπατήματος πριν το μάθημα;
* Τα σχολεία που έχουν περισσότερη γυμναστική, έχουν και καλύτερες ακαδημαϊκές επιδόσεις;

## Παράδειγμα

Οι ερευνητές δεν μπορούσαν να φτιάξουν κατευθείαν ένα ερωτηματολόγιο (quan),
γιατί πολύ απλά δεν ήξεραν ποιες συγκεκριμένες δραστηριότητες έκαναν τα σχολεία.

\

Ποιοτικό μέρος:

* Πήραν συνεντεύξεις σε βάθος από μόλις 15 άτομα (διευθυντές, γυμναστές και δασκάλους τάξης).
* Ανακάλυψαν ότι τα σχολεία χρησιμοποιούν δημιουργικούς τρόπους άσκησης, όπως το
  πρωινό περπάτημα ή σταθμούς με όργανα γυμναστικής στις αίθουσες.

\

Οι πληροφορίες αυτές χρησιμοποιήθηκαν για να σχηματιστούν ερωτήσεις.


## Παράδειγμα

Ποσοτικό μέρος:

* Βασισμένοι στις συνεντεύξεις, έφτιαξαν ένα ερωτηματολόγιο και το έστειλαν σε
  247 εκπαιδευτικούς σε 22 διαφορετικά σχολεία.
* Μέτρησαν τη συχνότητα των διαλειμμάτων για φυσική δραστηριότητα.
* Εκτίμησαν τη συσχέτιση των ωρών γυμναστικής με την επίσημη βαθμολογία του σχολείου.

## Παράδειγμα

**Ερώτημα:**  
Γνωρίζουν οι νηπιαγωγοί στο Χονγκ Κονγκ τον όρο «Σωματικός Γραμματισμός»
(Physical Literacy);


\

Ο όρος «Σωματικός Γραμματισμός» είναι πολύ καινούργιος και άγνωστος. Αν έδιναν
μόνο ένα ερωτηματολόγιο, οι δάσκαλοι μπορεί να απαντούσαν στην τύχη.

## Παράδειγμα

Ποιοτικό μέρος:

* Πήραν συνεντεύξεις (ατομικές και ομαδικές) από 45 εκπαιδευτικούς (διευθυντές και Ννηπιαγωγούς).
* Οι περισσότεροι δάσκαλοι δεν ήξεραν τον όρο.
* Φάνηκε ότι οι δάσκαλοι εστιάζουν μόνο στο σώμα (π.χ. «να μάθει να πιάνει την
  μπάλα») και ξεχνούν το συναίσθημα (π.χ. «να αγαπήσει την κίνηση»).

## Παράδειγμα

Ποσοτικό μέρος (επιβεβάιωση):

* Έδωσαν σύντομα ερωτηματολόγια με κλίμακα Likert (1-5) πριν και μετά τη
  συνέντευξη για να μετρήσουν το βαθμό εξοικείωσης με τον όρο.
* Ο μέσος όρος ήταν πολύ χαμηλός (2.22 στα 5).

## Παράδειγμα

Συμπεράσματα:

* Παρόλο που οι νηπιαγωγοί δεν ήξεραν τον όρο «Σωματικός Γραμματισμός» (θεωρία),
  στην πράξη έκαναν δραστηριότητες κίνησης. Όμως τις έκαναν αποσπασματικά, όχι
  οργανωμένα.
* Οι συνεντεύξεις αποκάλυψαν γιατί δεν κάνουν περισσότερη γυμναστική:
    * Έλλειψη χώρου (μικρές τάξεις).
    * Πίεση από τους γονείς να κάνουν μόνο μαθήματα (ανάγνωση/γραφή) και όχι παιχνίδι.

## Το μοντέλο ΠΟΣΟΤ-ποιοτ

* Ονομάζεται και ερμηνευτικό σχέδιο με μικτές μεθόδους.
* Τα ποσοτικά δεδομένα συλλέγονται πρώτα και έχουν μεγαλύτερο βάρος.

* Ποσοτικό μέρος:
  * Διαμόρφωση υπόθεσης, συλλογή και ανάλυση ποσοτικών δεδομένων.
  * Τα αποτελέσματα του ποσοτικού μέρους καθορίζουν 

