---
format:
  html:
    toc: true
    toc-depth: 5
    format-links: [pdf]
    css: ../styles.css
  typst: default
---

```{=typst}
#set text(font: "Noto Serif", lang: "el") // ensures bold + Greek shaping
    #let tbox(title, body) = rect(fill: luma(240), stroke: 1pt + gray, radius: 6pt, inset: 10pt)[
    #text(weight: "bold")[#title]
    #v(5pt)
    #body
  ]

#set list(indent: 18pt)
#set enum(indent: 18pt)
```

# Βήματα εκτέλεσης εκπαιδευτικής έρευνας

## Αναγνώριση του ερευνητικού θέματος

Συνήθως, ο/η εκπαιδευτικός στην καριέρα του καλείται να επιλύσει προβλήματα που
προκύπτουν κατά την εκπαιδευτική διαδικασία. Για την εκτέλεση της εκπαιδευτικής
έρευνας, ο/η ερευνητής/τρια καλείται ο/η ίδιος/α να διατυπώσει το πρόβλημα με το
οποίο θα ασχοληθεί. Το πρώτο βήμα για την εκτέλεση μίας εκπαιδευτικής έρευνας
είναι το θέμα να αποτελεί αντικείμενο ενδιαφέροντος, πρωτίστως για τον/την
επιστήμονα που θα κληθεί να την εκτελέσει.

Ένας/Μία ερευνητής/τρια μπορεί να αντλήσει τα πιθανά θέματα της έρευνας του/της
από διάφορες πηγές. Κάποιες από τις βασικότες πηγές άντλησης νέων θεμάτων για
την εκτέλεση της επισημονικής έρευνας μπορούν να είναι οι υπάρχουσες θεωρίες, οι
προσωπικές εμπειρίες, οι υπάρχουσες εργασίες και οι βιβλιογραφικές
αναζητήσεις. Ας τις πάρουμε με τη σειρά.

Τα ερευνητικά θέματα με το καθαρότερο νόημα προέρχονται από την ανάλυση
**θεωριών**. Θεωρία είναι ένα οργανωμένο σύνολο εννοιών, γενικεύσεων και αρχών
που μπορούν να διερευνηθούν. Υπάρχουν διάφοροι τρόποι που μπορεί μία θωρία να
χρησιμοποιηθεί για την εξαγωγή ενός ερευνητικού θέματος:

* _Μελέτη της σχέσης δύο εννοιών_ που συνδέει μία θεωρία, π.χ. η
  παιχνιδοκεντρική μάθηση και η προσοχή στην τάξη. Το θέμα μίας έρευνας μπορεί
  να αφορά την ισχύ και την κατεύθυνση της σχέσης αυτής.
* _Μελέτη των μηχανισμών_ με τους οποίους δημιουργούνται τα αποτελέσματα,
  π.χ. αναζήτηση των συγκεκριμένων χαρακτηριστικών των μαθητών που οδηγούν σε
  μεγαλύτερα οφέλη από την παιχνιδοκεντρική μάθηση.
* _Μελέτη των ορίων_ μίας θεωρίας, π.χ. έλεγχος της θεωρίας σε νέους
  (γενικότερους) πληθυσμούς.
  
Η **καθημερινή εμπειρία** μπορεί να αποτελέσει μία πολύ σημαντική πηγή άντλησης
ερευνητικών θεμάτων. Δεν υπάρχει εκπαιδευτικός που να μην έχει αναρωτηθεί κατά
τη διάρκεια της ημέρας αν κάτι θα μπορούσε να γίνει καλύτερα σε σχέση με την
συνηθισμένη πρακτική. Συνήθως, ο/η εκπαιδευτικός ασχολείται με αυτές τις σκέψεις
φευγαλέα, πριν επιστρέψει στις καθημερινές υποχρεώσεις. Αν όμως αυτές οι σκέψεις
οργανωθούν σωστά μπορούν να οδηγήσουν στη διατύπωση ερωτημάτων τα οποία
συνδέονται άμεσα με την εκπαιδευτική πρακτική. Το δύσκολο σε αυτή την προσέγγιση
είναι το κάτα πόσο μπορεί να μετατραπεί μία σκέψη ή μία απορία σε ένα ερώτημα
που μπορεί πραγματικά να ερευνηθεί.

Το θέμα μελλοντικών ερευνών πολύ συχνά μπορεί να προκύψει από την ανάγνωση και
ανάλυση ήδη **δημοσιευμένων εργασιών** και την ανάγκη **επαλήθευσης** των
αποτελεσμάτων τους. Υπάρχουν διάφορες προσεγγίσεις στην επαλήθευση δημοσιευμένων εργασιών:

* Η _άμεση επαλήθευση_ αφορά την όσο το δυνατόν πιο πιστή αναπαραγωγή των
  συνθηκών και των ενεργειών που αφορούσαν την αρχική εργασία.
* Η _εννοιολογική επαλήθευση (επέκταση)_ αφορά την διατήρηση της βασικής ιδέας
  της αρχικής εργασίας με την αλλαγή στη νέα έρευνα σημαντικών στοιχείων όπως η
  σύνθεση του πληθυσμού, το περιβάλλον, το χρονικό πλαίσιο ή ακόμα και μέρος του
  σχεδιασμού. Στόχος είναι ο έλεγχος της ανθεκτικότητας των αρχικών
  συμπερασμάτων και η δυνατότητα γενίκευσής τους.
  
Ένα μεγάλο μέρος των ερευνητικών θεμάτων που μπορούν να μελετηθούν προέρχεται
από την **βιβλιογραφική αναζήτηση**. Σκοπός είναι να μελετηθούν ενδελεχώς τα
επιστημονικά δεδομένα, ώστε να καταγραφεί τι είναι ήδη γνωστό και να
ανακαλυφθούν ελλείψεις ή κενά. Μία καλή ανασκόπηση δεν είναι απλώς μία συλλογή
πηγών αλλά προϋποθέτει την αναδιοργάνωση της βιβλιογραφίας ώστε να γίνουν
εμφανείς ομαδοποιήσεις και να αποκαλυφθούν τα ερευνητικά κενά.

Η διαδικασία διατύπωσης του ερευνητικού θέματος συνήθως προχωρά σταδιακά,
περιορίζοντας τις αρχικές διατυπώσεις σε πιο συγκεκριμένα και εύκολα
διασχειρίσιμα ερωτήματα. Ένα πολύ γενικό ερευνητικό ερώτημα μπορεί να οδηγήσει
σε πολύ εκτενή βιβλιογραφική ανασκόπηση, με σημαντικές δυσκολίες στην οργάνωση
την εκτέλεση και την ερμηνεία μίας έρευνας. Επομένως, ο **περιορισμός** της
αρχικής διατύπωσης διασφαλίζει την μεταφορά από ένα γενικό πεδίο (π.χ. η
ανάμειξη των γονέων) σε ένα συγκεκριμένο πρόβλημα που μπορεί να αναλυθεί σε ένα
συγκεκριμένο πλαίσιο. Ένα καλά ορισμένο ερώτημα οδηγεί:

* Σε μία καλά ορισμένη και σχεδιασμένη μελέτη που μπορεί πραγματικά να
  εκτελεστεί με βάση τις δεξιότητες, τους πόρους και το χρόνο που διαθέτει ο/η
  ερευνητής/τρια.
* Σε επιχειρησιακή ακρίβεια, δηλαδή τον ακριβή ορισμό εννοιών, μεταβλητών,
  πληθυσμών, χρονοδιαγραμμάτων.
* Διασφάλιση σεβασμού των ηθικών ορίων της επιστημονικής έρευνας.

Δυστυχώς, τα ερευνητικά θέματα τα οποία μπορούν ρεαλιστικά να αναλυθούν δεν
είναι απεριόριστα. Το ίδιο ισχύει και για τον χρόνο του/της
ερευνητή/τριας. Είναι σημαντικό ο/η ερευνητής/τρια να αποφύγουν να ασχοληθούν με
ένα θέμα το οποίο είτε έχει υπερ-αναλυθεί στο παρελθόν ή είναι τόσο
εξειδικευμένο ώστε τα αποτελέσματα να είναι πρακτικά αδύνατο να
γενικευθούν. Είναι προφανές ότι η επιλογή ενός καλού ερευνητικού θέματος δεν
είναι εύκολη υπόθεση. Παρακάτω περιγράφονται κάποια από τα χαρακτηριστικά τα
οποία θα συναντήσουμε σε καλά/επαρκή ερευνητικά θέματα:

* **Ενδιαφέρον:** Το ερευνητικό θέμα πρέπει να είναι ενδιαφέρον τόσο για τον/την
  ερευνήτρια όσο και για το κοινό στο οποίο θα απευθυνθούν τα αποτελέσματα της
  μελέτης. 
* **Δυνατότητα έρευνας:**: Το ερευνητικό θέμα πρέπει να μπορεί να διερευνηθεί με
  παρατηρήσιμα/μετρήσιμα στοιχεία. Στην ποιοτική έρευνα ένα καλό θέμα πρέπει να
  ορίζει τους συμμετέχοντες της μελέτης καθώς και τις μεταβλητές που θα
  μετρηθούν. Σε μία ποιοτική έρευνα θα περιγράφει επακριβώς το κεντρικό
  φαινόμενο τους συμμετέχοντες και το περιβάλλον.
* **Σημαντικό:** Το ερευνητικό θέμα πρέπει να επιλύσει μία διαπιστωμένη
  έλλειψη. Πρέπει να συμβάλει στη βελτίωση της πρακτικής ή στην προαγωγή της
  κατανόησης της εκπαιδευτικής θεωρίας.
* **Ηθικό:** Η μελέτη του θέματος που θα επιλεγεί πρέπει πάντοτε να σέβεται τα
  δικαιώματα των συμμετεχόντων.
* **Διαχειρίσιμο:** Η επιλογή ενός θέματος το οποίο εντάσσεται στα ερευνητικά
  ενδαιφέρονται του/της ερευνητή/τριας δεν αρκεί. Ο/Η ερευνητής/τρια πρέπει να
  διαθέτει τον απαραίτητο βαθμό εξειδίκευσης, να έχει πρόσβαση σε όλους τους
  απαιτούμενους πόρους και να έχει τον απαιτούμενο χρόνο στη διαθεσή του/της για
  την διεξαγωγή της μελέτης.
  
Συνήθως, την επιλογή και τον περιορισμό του ερευνητικού θέματος ακολουθεί μία
(γραπτή) **διατύπωση του θέματος**, δηλαδή μία σύντομη και ακριβής περιγραφή του
αντικειμένου της μελέτης, ώστε να μπορέσουν να στοιχειοθετηθούν τα επόμενα
βήματα. Η διατύπωση του θέματος προηγείται της διατύπωσης των ερευνητικών
ερωτημάτων και μπορεί να πάρει διαφορετικές μορφές αναλόγως την ερευνητική
προσέγγιση (ποσοτική/ποιοτική) αλλά και τις προτιμήσεις του/της
ερευνητή/τριας. 

Σε μία _ποσοτική έρευνα_, η διατύπωση του θέματος συνήθως περιλαμβάνει την
περιγραφή των μεταβλητών ενδιαφέροντος, τις μεταξύ τους σχέσεις καθώς και τους
συμμετέχοντες της έρευνας. Για παράδειγμα, η διατύπωση του ερευνητικού θέματος
θα μπορούσε να είναι:

> _"Το θέμα που θα διερευνηθεί είναι η επίδραση των καρτών με ερωτήσεις
> μαθηματικών στην ακρίβεια της μέτρησης κατά τη διάρκεια του παιχνιδιού
> προσποίησης στο μανάβικο στα παιδιά του νηπιαγωγείου."_

Σε αυτήν την περίπτωση ο πληθυσμός (παιδιά νηπιαγωγείου) και οι μεταβλητές
(κάρτες με ερωτήσεις μαθηματικών, ακρίβεια μέτρησης) είναι εντελώς ξεκάθαρα.


Σε μία _ποιοτική έρευνα_ το θέμα περιγράφεται με πιο γενική διατύπωση, καθώς ο/η
ερευνητής/τρια χρειάζεται να διαθέσει αρκετό χρόνο στο περιβάλλον της έρευνας
ώστε να ανακύψει το θέμα της μελέτης. Σε μία ποιοτική έρευνα, το θέμα της
έρευνας εξειδικεύεται καθώς ο/η ερευνητής/τρια μαθαίνει περισσότερα για το
πλαίσιο μέσα στο οποίο πραγματοποιείται η έρευνα. Για παράδειγμα, η διατύπωση
του ερευνητικού θέματος θα μπορούσε να είναι:

> _"Σκοπός της μελέτης είναι να περιγράψει τη φύση της ενασχόλησης των παιδιών
> με τα μαθηματικά. Στόχος είναι να συγκεντρωθούν λεπτομέρειες σχετικά με τους
> τρόπους με τους οποίους τα παιδιά εισάγονται στα μαθηματικά και διατηρούν το
> ενδιαφέρον τους για αυτά."_

Την επιλογή του ερευνητικού θέματος, την εξειδίκευση και διατύπωσή του ακολουθεί
η **διατύπωση των ερευνητικών ερωτημάτων**. Τα ερωτήματα αυτά αποτελούν την
ακριβή περιγραφή των ζητημάτων που θα απαντηθούν από τη μελέτη που
πραγματοποιείται. Επίσης, αποτελούν και μία επιβεβαίωση ότι το θέμα που έχει
επιλεχθεί μπορεί πραγματικά να απαντηθεί με την εκτέλεση της εν λόγω
μελέτης. Στην περίπτωση _ποσοτικών μελετών_ τα ερευνητικά ερωτήματα αφορούν την
περιγραφή και την ποσοτικοποίηση σχέσεων μεταξύ των μεταβλητών. Για παράδειγμα
ένα από τα ερευνητικά ερωτήματα της προηγούμενης ποσοτικής μελέτης θα μπορούσε να
είναι:

> _"Η ακρίβεια της μέτρησης είναι μεγαλύτερη κατά τη διάρκεια των συνεδριών με
> κάρτες ερωτήσεων μαθηματικών συζητήσεων σε σύγκριση με τις συνεδρίες χωρίς
> αυτές;"_


Στην περίπτωση _ποιοτικών μελετών_ συνήθως διατυπώνεται ένα βασικό ερώτημα με
έναν μικρό αριθμό υπο-ερωτημάτων. Για παράδειγμα, ένα από τα ερευνητικά
ερωτήματα της προηγούμενης ποιοτικής μελέτης θα μπορούσε να είναι:

> _"Ποιες στρατηγικές χρησιμοποιούν τα παιδιά για να ασχοληθούν με τη μάθηση των
> μαθηματικών; Πώς αυτές οι στρατηγικές διατηρούν τη συμμετοχή των μαθητών στη
> μάθηση των μαθηματικών; Πώς η ενασχόληση με το περιεχόμενο των μαθηματικών
> επηρεάζει τη στάση των μαθητών απέναντι στα μαθημα;"_

Το επόμενο βήμα στον ορισμό ενός ερευνητικού θέματος είναι η διατύπωση της
**υπόθεσης**, δηλαδή της πρόβλεψης του/της ερευνητή/τριας για το αποτέλεσμα της
μελέτης και τις απαντήσεις στα ερευνητικά ερωτήματα. Ένα ερευνητικό θέμα μπορεί
να περιλαμβάνει τη διατύπωση μίας ή περισσότερων υποθέσεων. Υποθέσεις
διατυπώνονται τόσο στην ποσοτική όσο και στην ποιοτική έρευνα, αλλά η φύση κάθε
προσέγγισης διαφέρει σημαντικά.

Οι ερευνητικές υποθέσεις αποτελούν αναπόσπαστο κομμάτι της _ποσοτικής
έρευνας_. Συνήθως, εξάγονται με βάση τα όσα προβλέπει μία επιστημονική θεωρία ή
από τα ευρήματα που παρουσιάζονται στην επιστημονική βιβλιογραφία. Τα
χαρακτηριστικά μίας καλής ερευνητικής υπόθεσης είναι:

* Η υπόθεση πρέπει να στηρίζεται σε μία στέρεη λογική και να συνάδει με τις
  επικρατούσες θεωρίες και τα αποτελέσματα προηγούμενων μελετών.
* Η υπόθεση πρέπει να παρέχει μία λογική εξήγηση για το προβλεπόμενο αποτέλεσμα.
* Η υπόθεση περιγράφει συνοπτικά και με σαφήνεια την αναμενόμενη σχέση ή διαφορά
  μεταξύ των μεταβλητών.
* Η υπόθεση πρέπει να μπορεί να ελεγχθεί μέσα σε λογικά χρονικά πλαίσια.

Οι υποθέσεις, καθώς είναι προϊόντα συλλογισμού, μπορούν να είναι είτε
_επαγωγικές_ είτε _παραγωγικές_. Στην περίπτωση μίας επαγωγικής ερευνητικής
υπόθεσης, οι παρατηρήσεις του/της ερευνητή/τριας σε έναν περιορισμένο αριθμό
περιπτώσεων γενικεύονται σε μία πρόβλεψη για το αποτέλεσμα της έρευνας. Στην
περίπτωση μίας παραγωγικής ερευνητικής υπόθεσης, η πρόβλεψη μίας υπάρχουσας
θεωρίας χρησιμοποιείται για να προβλέψει το αποτέλεσμα της έρευνας.

Καθώς στην ποσοτική έρευνα οι υποθέσεις προβλέπουν (ποσοτικοποιούν) τις σχέσεις
μεταξύ μεταβλητών, μπορούμε να διακρίνουμε τις ερευνητικές υποθέσεις σε:

* **Μη-κατευθυντικές ερευνητικές υποθέσεις**: Δηλώνουν ότι υπάρχει μία σχέση ή
  διαφορά μεταξύ των μεταβλητών χωρίς να μας ενδιαφέρει η κατεύθυνσή της,
  π.χ. υπάρχει σχέση μεταξύ μίας παρέμβασης και της επίδοσης των μαθητών.
* **Κατευθυντικές ερευνητικές υποθέσεις**: Δηλώνουν ότι υπάρχει μία σχέση ή
  διαφορά μεταξύ των μεταβλητών με συγκεκριμένη κατεύθυνση, π.χ. η παρέμβαση
  βελτιώνει την επίδοση των μαθητών.

Τέλος, υπάρχει και η επονομαζόμενη **μηδενική υπόθεση** (null hypothesis) η
οποία προβλέπει ότι δεν υπάρχει καμία σχέση μεταξύ των μεταβλητών.

Στην περίπτωση της _ποιοτικής έρευνας_ οι στόχοι και οι στρατηγικές των
ποιοτικών ερευνητών μπορεί να διαφέρουν σημαντικά. Συνήθως, στα πλαίσια της
ποιοτικής έρευνας δεν διατυπώνονται επίσημες υποθέσεις, πριν από την διεξαγωγή
της μελέτης. Ωστόσο, στα πλαίσια μιας ποιοτικής μελέτης μπορεί να αναπτυχθούν
κατευθυντήριες υποθέσεις για την προτεινόμενη έρευνα. Αντί να ελγχθούν υποθέσεις
σε μία ποιοτική έρευνα είναι πολύ πιο πιθανό να διατυπωθούν νέες υποθέσεις. 

Η επαγωγική διαδικασία που χρησιμοποιείται ευρέως στην ποιοτική έρευνα βασίζεται
στην παρατήρηση μοτίβων και συσχετισμών στο φυσικό περιβάλλον των συμμετεχόντων,
χωρίς προηγούμενες υποθέσεις ή εικασίες σχετικά με το τι θα μελετήσουν και θα
παρατηρήσουν οι ερευνητές. Η απροθυμία των ποιοτικών ερευνητών να προσδιορίσουν
αμέσως τις μεταβλητές και τις προβλέψεις πηγάζει από την άποψη ότι τα πλαίσια
και οι συμμετέχοντες διαφέρουν και πρέπει να κατανοηθούν με τους δικούς τους
όρους πριν ο ερευνητής μπορέσει να αρχίσει να διατυπώνει υποθέσεις ή να
κρίνει. Έτσι, οι ποιοτικοί ερευνητές έχουν μεγαλύτερη διακριτική ευχέρεια στο να
καθορίζουν πότε και πώς θα εξετάσουν ή θα περιορίσουν ένα θέμα.
