---
format:
  html:
    toc: true
    toc-depth: 5
    format-links: [pdf]
    css: ../styles.css
  typst: default
---

```{=typst}
#set text(font: "Noto Serif", lang: "el") // ensures bold + Greek shaping
    #let tbox(title, body) = rect(fill: luma(240), stroke: 1pt + gray, radius: 6pt, inset: 10pt)[
    #text(weight: "bold")[#title]
    #v(5pt)
    #body
  ]
```

# Ποσοτική έρευνα

## Έρευνα ερωτηματολογίου

Η _έρευνα ερωτηματολογίου_ είναι συστηματική συλλογή τυποποιημένων,
ποσοτικοποιήσιμων πληροφοριών από όλα τα μέλη ενός πληθυσμού ή από ένα
αντιπροσωπευτικό δείγμα, με σκοπό την περιγραφή στάσεων, αντιλήψεων,
συμπεριφορών ή χαρακτηριστικών. Το έρευνα ερωτηματηματολογίου μπορεί να είναι
συγχρονική (μία χρονική στιγμή) ή διαχρονική (πολλές μετρήσεις στον χρόνο).

Σε μία _συγχρονική μελέτη_ τα δεδομένα συλλέγονται σε μία χρονική στιγμή ή μέσα
σε σύντομο, ενιαίο χρονικό παράθυρο από τα άτομα/ομάδες που μας
ενδιαφέρουν. Συχνά περιλαμβάνει πολλαπλές κατηγορίες (π.χ. φύλο, τάξη/ηλικία)
ώστε να γίνουν συγκρίσεις μεταξύ τους. Το βασικό πλεονέκτημα μίας συγχρονικής
μελέτης είναι ότι επιτρέπει τη συλλογή στοιχείων από πολλούς και διαφορετικούς
τύπους συμμετεχόντων γρήγορα. Δίνει μια «φωτογραφία του τώρα»: Δεν τεκμηριώνει
την πορεία στο χρόνο ούτε αιτιότητα, επειδή δεν διασφαλίζεται η χρονική
ακολουθία αίτιου-αποτελέσματος.

Σε μία _διαχρονική μελέτη_ τα ίδια φαινόμενα μετρώνται επαναλαμβανόμενα σε δύο ή
περισσότερες χρονικές στιγμές με χρήση τυποποιημένων εργαλείων
(ερωτηματολόγια/δομημένες συνεντεύξεις). Σκοπός είναι η μελέτη της μεταβολής,
της σταθερότητας ή της χρονικής ακολουθίας στάσεων, συμπεριφορών ή άλλων
χαρακτηριστικών σε επίπεδο ατόμων, ομάδων ή πληθυσμών. Σε αντίθεση με τις
συγχρινικές μελέτες που «παγώνουν» την πραγματικότητα σε μία χρονική τομή, οι
διαχρονικές εστιάζουν στο πώς και πόσο αλλάζουν τα πράγματα με τον χρόνο.

Ο/Η ερευνητής/τρια κατά το σχεδιασμό μίας διαχρονικής μελέτης είναι απαραίτητο
να:

1. Καθορίσει τον αριθμό και την απόσταση μεταξύ των στιγμών εκτέλεσης των μετρήσεων,
   π.χ. πόσες μετρήσεις θα χρειαστούν για να μπορέσει να περιγραφεί επαρκώς η
   εξέλιξη ενός φαινομένου.
2. Αποφασίσει το μέγεθος του δείγματος ώστε να αντιμετωπιστεί και η φθορά του δείγματος (δε
   θα έχουμε όλες τις μετρήσεις για όλους τους συμμετέχοντες στη μελέτη).
3. Διασφαλίσει την ισοδυναμία των μετρήσεων στο χρόνο. Κάθε φορά, τα εργαλεία
   και οι κλίμακες που χρησιμοποιούνται πρέπει να μετρούν το ίδιο αντικείμενο,
   ώστε οι συγκρίσεις να έχουν νόημα.
   
## Συσχετιστική έρευνα

Η _συσχετιστική έρευνα_ είναι μη πειραματικός ποσοτικός σχεδιασμός όπου ο/η
ερευνητής/τρια μετρά δύο ή περισσότερες ποσοτικές μεταβλητές στο ίδιο δείγμα και
εξετάζει αν και σε ποιο βαθμό αυτές συνδέονται μεταξύ τους. Η σχέση συνοψίζεται
με συντελεστή συσχέτισης ο οποίος συνήθως κειμένεται μεταξύ −1 και +1 που
δείχνει ισχύ και κατεύθυνση της σχέσης. Θετικός συντελεστής συσχέτισης σημαίνει
«όσο αυξάνει η μία μεταβλητή τείνει να αυξάνει και η άλλη», αρνητικός το
αντίθετο, και 0 «καμία γραμμική σχέση».

Είναι σημαντικό να θυμόμαστε ότι συσχέτιση από μόνη της δεν μπορεί να ερμηνευθεί
ως αιτιότητα. Για παράδειγμα, έστω ότι μετρήσαμε σε ένα δείγμα από τα
νηπιαγωγεία της χώρας, το ύψος των μαθητών και τον αριθμό των λέξεων που
χρησιμοποίησαν για να περιγράψουν μία εικόνα. Έστω ότι βρέθηκε θετική συσχέτιση
μεταξύ των δύο μετρήσεων (σε παιδιά με μεγαλύτερο ο ύψος, ο αριθμός των λέξεων
έτεινε να είναι υψηλότερος). Αυτό δε σημαίνει το ύψος προκάλεσε την αύξηση στον
αριθμό των λέξεων. Μια πιο πιθανή εξήγηση είναι ότι η ηλικία είναι ο κοινός
παράγοντας (αιτία) για την αύξηση και των δύο μετρήσεων.

Ακόμα και αν δεν μπορούμε να συμπεράνουμε αιτιότητα με μία συσχετιστική μελέτη,
μπορούμε να χρησιμοποιήσουμε αυτό το είδος των μελετών για την περιγραφή τάσεων
μέσα στον πληθυσμό, π.χ. σε ποιο βαθμό συνδέονται το ύψος και ο αριθμός των
λέξεων του προηγούμενου παραδείγματος; Επίσης, μπορούμε να χρησιμοποιήσουμε μία
συσχετιστική μελέτη για να κάνουμε προβλέψεις για τις τιμές παραγόντων που μας
ενδιαφέρουν. Στο προηγούμενο παράδειγμα, θα μπορούσαμε να προτείνουμε ένα
μοντέλο για την πρόβλεψη του αριθμού των λέξεων αν γνωρίζουμε το ύψος των
μαθητών, ακόμα και αν δε γνωρίζουμε την ηλικία τους.

## Αιτιώδης-συγκριτική έρευνα

Η αιτιώδης-συγκριτική έρευνα είναι ποσοτική προσέγγιση όπου ο/η ερευνητής/τρια
επιχειρεί να εντοπίσει την «αιτία» ή τον λόγο για ήδη υπάρχουσες διαφορές
ανάμεσα σε ομάδες ή άτομα μεταβλητής. Συχνά αποκαλείται ex post facto («μετά τα
γεγονότα») επειδή τόσο το «αποτέλεσμα» όσο και η φερόμενη «αιτία» έχουν ήδη
συμβεί και μελετώνται αναδρομικά. Η συνηθισμένη δομή μίας αιτιώδους-συγκριτικής
μελέτης περιλαμβάνει την επιλογή δύο (ή περισσότερων) υφιστάμενων ομάδων που
διαφέρουν ως προς ένα χαρακτηριστικό με στόχο τη σύγκριση ως προς ένα
προκαθορισμένο χαρακτηριστικό.

Οι στόχοι μιας αιτιώδους-συγκριτικής μελέτης συνήθως είναι:

* Η διερεύνηση πιθανών αιτίων για υφιστάμενες διαφορές (π.χ. αν η προσχολική
  φοίτηση με υψηλότερη οικονομική επίδοση).
* Η προκαταρκτική τεκμηρίωση για την εκτέλεση μελλοντικής πειραματικής μελέτης
  (π.χ. αξιολόγηση του οφέλους μιας πιλοτικής εφαρμογής).
* Η μελέτη παραγόντων που δεν μπορούν να χειραγωγηθούν (π.χ. φύλο) ή που δεν
  μπορούν με ηθικό τρόπο να μελετηθούν (π.χ. κάπνισμα κατά την εγκυμοσύνη).

Η αιτιώδης-συγκριτική έρευνα μοιάζει περισσότερο με περιγραφική έρευνα, γιατί
περιγράφει υφιστάμενες καταστάσεις, ενώ συγχρόνως προσπαθεί να αποδώσει και τις
αιτίες ύπαρξης ή δημιουργίας των διαφορών. Ωστόσο, δεν περιλαμβάνει το στοιχείο
του πειραματισμού. Οι ομάδες που συγκρίνονται είναι ήδη σχηματισμένες και δεν
υπάρχει τυχαιοποίηση. Διαφέρει από τη συσχετιστική έρευνα καθώς εστιάζει σε
διαφορές μεταξύ ομάδων (π.χ. φύλο, περιοχή φοίτησης). Αντίθετα, σε μία
συσχετιστική μελέτη εξετάζονται οι σχέσεις μεταξύ μεταβλητών μέσα στην ίδια
ομάδα.

Ο σχεδιασμός μίας αιτιώδους-συγκριτικής μελέτης μπορεί να είναι είτε αναδρομική
είτε προοπτική. Σε μία αναδρομική μελέτη ο/η ερευνητής/τρια ξεκινά από ένα
αποτέλεσμα (π.χ. χαμηλή επίδοση, άγχος στην τάξη) που ήδη υφίσταται και προχωρά
προς τα πίσω στον χρόνο για να εντοπίσει πιθανούς παράγοντες που προηγήθηκαν και
είναι πιθανό να εξηγούν τις υφιστάμενες διαφορές. Σε μία αναδρομική μελέτη
συνήθως χρησιμοποιούνται αρχειακά δεδομένα (π.χ. μητρώα, παλαιότερες
αξιολογήσεις) ή αναδρομικές ερωτήσεις στους συμμετέχοντες (π.χ. ανάκληση
εμπειριών).

Μία αναδρομική μελέτη είναι ευκολότερο και οικονομικότερο να πραγματοποιηθεί
καθώς απαιτείται μόνο η πρόσβαση σε αρχειακά δεδομένα ή σε ανθρώπους που
συμμετείχαν σε προηγούμενες μελέτες. Ωστόσο, καθώς τα δεδομένα συλλέγονται εκ
των υστέρων, η χρονική ακολουθία δεν τεκμηριώνει συνήθως ισχυρά μία αιτιακή
σχέση. Πολλές διαφορετικές ερμηνείες μπορούν να αποδοθούν στις διαφορές που
καταγράφηκαν. Επίσης, στην περίπτωση αναδρομικών ερωτήσεων στους συμμετέχοντες,
είναι πιθανό να υπάρξει σοβαρό σφάλμα ανάκλησης των εμπειριών (π.χ. οι
ερωτώμενοι να μην θυμούνται ακριβώς τι προηγήθηκε και πότε).
