---
title: "Μεθοδολογία Εκπαιδευτικής Έρευνας (0110Υ)"
subtitle: "Χειμερινό εξάμηνο 2025-2026"
author: "Αλέξανδρος Ρέκκας"
date: "2025-11-20"
format:
  revealjs:
    theme: [default, custom.scss]
    logo: logo.jpg
    footer: "Μεθοδολογία Εκπαιδευτικής Έρευνας: _7ο Μάθημα_"
    slide-number: c/t
    incremental: false
    transition: slide
    background-transition: fade
    highlight-style: monokai
    code-line-numbers: false
    preview-links: auto
    width: 1280
    height: 720
lang: el
---

# Υπενθύμιση

# Επιλογή δείγματος στην ποσοτική έρευνα

## Γενικά

\

* Είναι αδύνατο να συλλέξουμε πληροφορίες για έναν ολόκληρο πληθυσμό.
* Μπορεί να είναι πολυπληθής ή γεωγραφικά διάσπαρτος.
* Έχουμε δυνατότητα πρόσβασης σε ένα υποσύνολο του πληθυσμού αυτού.
* Αν επιλέξουμε σωστά το δείγμα τα συμπεράστα είναι "_γενικεύσιμα_".


## Καθορισμός του πληθυσμού

Παραδείγματα πληθυσμών:

* Όλοι οι μαθητές νηπιαγωγείου της χώρας.
* Όλοι οι μετανάστες μαθητές νηπιαγωγείου της Δυτικής Μακεδονίας.
* Όλοι οι μαθητές νηπιαγωγείου της Φλώρινας με αυτισμό.


## Καθορισμός του πληθυσμού

\

Δύο σημαντικά χαρακτηριστικά των πληθυσμών:

* Μπορεί να έχουν οποιοδήποτε μέγεθος και να καλύπτουν οποιαδήποτε γεωγραφική
  περιοχή.
* Ο/Η ερευνητής/τρια σπάνια έχει πρόσβαση σε ολόκληρο τον πληθυσμό.

## Καθορισμός του πληθυσμού

\

Μπορούμε να χωρίσουμε τον πληθυσμό δύο κατηγορίες:

* Τον πληθυσμό στόχο
* Τον προσβάσιμο πληθυσμό

## Δειγματοληψία

\

Σε μια ποσοτική έρευνα λέμε ότι το δείγμα είναι καλό αν είναι αντιπροσωπευτικό του πληθυσμού.

\

Τι είναι "_αντιπροσωπευτικό_";

\

Η **πιθανοτική δειγματοληψία** οδηγεί σε αντιπροσωπευτικά δείγματα.


## Απλή τυχαία δειγματοληψία

\

> **Ορισμός**
> 
> Κάθε μέλος του πληθυσμού έχει την ίδια πιθανότητα να συμμετέχει στο δείγμα. Η
> επιλογή ενός ατόμου δεν επηρεάζει τις πιθανότητες επιλογής ενός άλλου ατόμου.


## Απλή τυχαία δειγματοληψία -- Διαδικασία

1. Εντοπίζουμε και ορίζουμε τον πληθυσμό.
2. Καθορίζουμε το επιθυμητό μέγεθος του δείγματος.
3. Καταγράφουμε τα μέλη ολόκληρου του πληθυσμού.
4. Αριθμούμε διαδοχικά τα μέλη ολόκληρου του πληθυσμού.
5. Επιλέγουμε αυθαίρετα έναν αριθμό από έναν πίνακα τυχαίων αριθμών.
6. Από τον αριθμό αυτόν κρατάμε τα τελευταία $n$ ψηφία
7. Αν ο αριθμός αυτός αντιστοιχεί σε άτομο του πληθυσμού τον κρατάμε.
8. Πηγαίνουμε στον επόμενο αριθμό της στήλης και επιστρέφουμε στο βήμα 6.

## Απλή τυχαία δειγματοληψία -- Παράδειγμα

\

Έστω ότι έχουμε έναν πληθυσμό 500 ατόμων και θέλουμε να εξάγουμε ένα τυχαίο
δείγμα 5 ατόμων.

\

```{r}
matrix(sample(10000:99999, 100, replace = TRUE), nrow = 10, ncol = 10)
```


## Απλή τυχαία δειγματοληψία -- Πλεονεκτήματα

* Είναι η καλύτερη προσέγγιση για την εξαγωγή ενός αντιπροσωπευτικού δείγματος.
* Οι όποιες διαφορές προκύψουν μεταξύ δείγματος και πληθυσμού είναι αποτέλεσμα
  της τύχης.
* Είναι η προαπαιτούμενη διαδικασία για τις περισσότερες στατιστικές αναλύσεις.

## Απλή τυχαία δειγματοληψία -- Μειονέκτημα

* Η αντιπροσώπευση οποιασδήποτε υποομάδας του πληθυσμού είναι **πιθανή** αλλά **όχι βέβαιη**.

## Στρωματοποιημένη δειγματοληψία

\

> **Ορισμός**
>
>Στρωματοποιημένη δειγματοληψία είναι η τυχαία δειγματοληψία από υπο-ομάδες
> (στρώματα) του πληθυσμού. Εγγυάται την αντιπρσώπευση όλων των υπο-ομάδων στο
> δείγμα.

## Αναλογική στρωματοποιημένη δειγματοληψία

\

* Μόνο όταν είναι γνωστή η αναλογία όλων των υπο-ομάδων του πληθυσμού.
* [ ] Συνηθισμένες μεταβλητές: φύλο, κοινωνικό/οικονομικό επίπεδο, μορφωτικό επίπεδο

## Ισομεγέθη δείγματα

\

> **Ορισμός**
>
> Στρωματοποιημένη δειγματοληψία όπου όλες οι υπο-ομάδες έχουν τον ίδιο αριθμό
> ατόμων στο τελικό δείγμα.


## Ισομεγέθη δείγματα

\

Διαδικασία:

1. Εντοπίζουμε και ορίζουμε τον πληθυσμό
2. Καθορίζουμε το επιθυμητό μέγεθος του δείγματος.
3. Εντοπίζουμε τη μεταβλητή στρωματοποίησης και όλα τα στρώματα.
4. Ταξινομούμε τα μέλη του πληθυσμού ως μέλη ενό στρώματος.
5. Εκτελούμε απλή τυχαία δειγματοληψία στο εσωτερικό κάθε στρώματος.

## Δειγματοληψία κατά συστάδες

\

> **Ορισμός**
>
> Τυχαία επιλογή ολόκληρων ομάδων. Στη δειγματοληψία κατά συτάδες η μονάδα της
> δειγματοληψίας δεν είναι το άτομο αλλά η ομάδα (συστάδα). Παραδείγματα συτάδων
> είναι το νηπιαγωγείο, η τάξη, η γειτονιά κτλ.

\

Πολύ **χρήσιμη** όταν δεν μπορούμε να γνωρίζουμε κάθε μέλος του πληθυσμού.

## Δειγματοληψία κατά συστάδες

Διαδικασία:

1. Εντοπίζουμε και ορίζουμε τον πληθυσμό
2. Καθορίζουμε το επιθυμητό μέγεθος του δείγματος.

## Δειγματοληψία κατά συστάδες

3. Εντοπίζουμε και καθορίζουμε μία λογική συστάδα.
4. Φτιάχνουμε κατάλογο με όλες τις συστάδες.
5. Εκτιμούμε το μέσο αριθμό μελών της κάθε συστάδας.
6. Καθορίζουμε τον αριθμό των συστάδων που θα χρειαστούμε.
6. Επιλέγουμε με απλή τυχαία δειγματοληψία τον απαιτούμενο αριθμό συστάδων.
7. Συμπεριλαμβάνουμε στη μελέτη όλα τα μέλη των επιλεγμένων συστάδων.

## Δειγματοληψία κατά συστάδες

* Οι πιθανότητες να μην είναι αντιπροσωπευτικό το δείγμα είναι μεγάλες.
* Απαιτούνται πιο σύνθετες στατιστικές μέθοδοι για την ανάλυση του δείγματος.

## Μέγεθος του δείγματος

Το μέγεθος του δείγματος τις περισσότερες φορές καθορίζεται από τη είδος της
μελέτης που θέλουμε να πραγματοποιήσουμε.

\

Γενικές οδηγίες:

* Για μικρούς πληθυσμους (πχ 100 ατόμων) δεν έχει νόημα η δειγματοληψία.
* Εάν το μέγεθος του πληθυσμού είναι 500 (+/- 100) τότε δείγμα 50%.
* Εάν το μέγεθος του πληθυσμού είναι 1500 (+/- 100) τότε δείγμα 20%.
* Πάνω από ένα όριο (γύρω στο 5000) ένα δείγμα 400 ατόμων είναι αρκετό.

## Σφάλματα

* Η πιθανοτική δειγματοληψία περιλαμβάνει την έννοια του τυχαίου.
* Διαφορές μεταξύ δείγματος και πληθυσμού εξαιτίας της τύχης και μόνο είναι δυνατές.
* Οι διαφορές αυτές ονομάζανται σφάλματα της δειγματοληψίας

## Μεροληψία

* Μεροληψία αποτελούν το συστηματικό σφάλμα.
* Παράδειγμα: Γνώμη των φοιτητών για το αλκοόλ έξω από ένα μπαρ.
* Η μεροληψία περιορίζει τα συμπεράσματα σε έναν διαφορετικό πληθυσμό.

## Μη πιθανοτική δειγματοληψία

> **Ορισμός**
>
> Mη πιθανοτική δειγματοληψία είναι η επιλογή δείγματος με μία τεχνική που
> δεν επιτρέπει στον/στην ερευνητή/τρια να προσδιορίσει την πιθανότητα επιλογής
> του κάθε μέλους του πληθυσμού.

\

Επομένως, είναι αδύνατο να προσδιοριστεί και ο πληθυσμός από τον οποίο προήλθε
το δείγμα.


## Δειγματοληψία ευκολίας

* Συμμετοχή στο δείγμα μόνο των ατόμων που ήταν διαθέσιμα τη στιγμή της
  δειγματοληψίας.
* Αυτοί που προσφέρονται να απαντήσουν μπορεί να είναι συστηματικά διαφορετικοί
  από αυτούς που αρνούνται.
* Τα συμπεράσματα δεν μπορούν να γενικευθούν στον πληθυσμό.

## Δειγματοληψία σκοπιμότητας

* Επιλογή ενός δείγματος που θεωρείται αντιπροσωπευτικό με βάση την κρίση
  του/της ερευνητή/τριας.
* Μπορεί να υποστηριχθεί καλύτερα από μία δειγματοληψία ευκολίας.
* Εξαρτάται από την ακρίβεια των κριτηρίων του/της ερευνητή/τριας.

## Ποσοστική δειγματοληψία

* Δειγματοληψία με βάση απαιτούμενους αριθμούς ατόμων.
* Τα εύκολα προσεγγίσιμα άτομα  συμπεριλαμβάνονται πιο συχνά στο δείγμα.

# Επιλογή δείγματος στην ποιοτική έρευνα

## Γενικά

\

* Συνήθως περιλαμβάνει την επιλογή μικρού αριθμού ατόμων.
* Δεν ενδιαφέρει τόσο πολύ η αντιπροσωπευτικότητα.
* Οι συμμετέχοντες διαλέγονται με βάση την ικανότητά τους να παρέχουν το βάθος
  της πληροφορίας που χρειάζεται.
  
  
## Η λογική της επιλογής συμμετεχόντων

\

* Συμμετέχοντες σπάνια διατεθιμένοι να σπαταλήσουν τόσο πολύ χρόνο.
* Απαραίτητη η προεργασία ώστε να εντοπιστούν άτομα με τα κατάλληλα
  χαρακτηριστικά.

## Είδη δειγματοληψίας

\

* **Δειγματοληψία έντασης:**  
  Επιλογή συμμετεχόντων που επιτρέπουν την μελέτη διαφορετικών επιπέδων του
  ερευνητικού θέματος (π.χ. έμπειροι-άπειροι εκπαιδευτικοί).

\
  
* **Ομογενής δειγματοληψία:**  
Επιλογή συμμετεχόντων με παρόμοια εμπειρία.


## Είδη δειγματοληψίας

\

* **Δειγματοληψία κριτηρίου:**  
Επιλογή όλων των συμμετεχόντων που πληρούν ένα σύνολο κριτηρίων/χαρακτηριστικών.

\

* **Δειγματοληψία χιονοστιβάδας:**  
Επιλογή λίγων ανθρώπων που ταιριάζουν στις ανάγκες της έρευνας. Στη συνέχεια
χρήση αυτών των συμμετεχόντων για να εντοπιστούν επιπλέον συμμετέχοντες.

## Είδη δειγματοληψίας

* **Τυχαία δειγματοληψία σκοπιμότητας:**  
Επιλογή μίας δεξαμενής συμμετεχόντων (περισσότεροι από όσους
χρειάζονται). Επιλογή τυχαία από την δεξαμενή.

# Ευχαριστώ
