---
title: "Μεθοδολογία Εκπαιδευτικής Έρευνας (0110Υ)"
subtitle: "Χειμερινό εξάμηνο 2025-2026"
author: "Αλέξανδρος Ρέκκας"
date: "2025-10-30"
format:
  revealjs:
    theme: [default, custom.scss]
    logo: logo.jpg
    footer: "Μεθοδολογία Εκπαιδευτικής Έρευνας | Παιδαγωγικό Τμήμα Νηπιαγωγών - ΠΔΜ"
    slide-number: c/t
    incremental: false
    transition: slide
    background-transition: fade
    highlight-style: monokai
    code-line-numbers: false
    preview-links: auto
    width: 1280
    height: 720
lang: el
---

# Βήματα της επιστημονικής έρευνας

## Υπενθύμιση

Η εκπαιδευτική έρευνα είναι μια συστηματική διαδικασία που ακολουθεί
συγκεκριμένα βήματα για τη διερεύνηση εκπαιδευτικών προβλημάτων:

1. Προσδιορισμός του ερευνητικού θέματος
1. Βιβλιογραφική ανασκόπηση
1. Προετοιμασία ερευνητικού σχεδίου
1. Προσδιορισμός δείγματος και συλλογή δεδομένων
1. Ανάλυση δεδομένων
1. Εξαγωγή συμπερασμάτων

# Προσδιορισμός του Ερευνητικού Θέματος

## Γενικά

* Ο προσδιορισμός ενός ερευνητικού θέματος είναι το πρώτο και πιο κρίσιμο βήμα
  στην ερευνητική διαδικασία.
* Ένα καλά καθορισμένο θέμα παρέχει την εστίαση και τη δομή για όλα τα επόμενα
  βήματα.

## Εύρεση ερευνητικών ζητημάτων
### Θεωρία

* Τα ερευνητικά θέματα με το καθαρότερο νόημα προέρχονται από την ανάλυση θεωριών.

> **Ορισμός**
>
>Θεωρία είναι ένα οργανωμένο σύνολο εννοιών, γενικεύσεων και αρχών που μπορούν να
>διερευνηθούν. 

## Εύρεση ερευνητικών ζητημάτων
### Θεωρία

* Μελέτη της σχέσης μεταξύ δύο εννοιών
* Μελέτη των μηχανισμών που δημιουργούνται τα αποτελέσματα
* Μελέτη των ορίων μίας θεωρίας



## Εύρεση ερευνητικών ζητημάτων
### Πρακτική εμπειρία

* Η καθημερινή εμπειρία στο νηπιαγωγείο είναι μια από τις πιο σημαντικές πηγές
  έμπνευσης.
* Προβλήματα, απορίες και παρατηρήσεις από την πρακτική άσκηση ή την εργασία
  μπορούν να μετατραπούν σε ερευνητικά ερωτήματα.

## Εύρεση ερευνητικών ζητημάτων
### Δημοσιευμένο έργο

\

> **Άμεση επαλήθευση**
> 
> _Όσο το δυνατόν πιο πιστή αναπαραγωγή των συνθηκών και των ενεργειών που
> αφορούσαν την αρχική εργασία._

## Εύρεση ερευνητικών ζητημάτων
### Δημοσιευμένο έργο

\

> **Εννοιολογική επαλήθευση**
>
> _Διατήρηση της βασικής ιδέας της αρχικής εργασίας με την αλλαγή στη νέα έρευνα
> σημαντικών στοιχείων όπως η σύνθεση του πληθυσμού, το περιβάλλον, το χρονικό
> πλαίσιο ή ακόμα και μέρος του σχεδιασμού. Στόχος είναι ο έλεγχος της
> ανθεκτικότητας των αρχικών συμπερασμάτων και η δυνατότητα γενίκευσής τους._

## Εύρεση ερευνητικών ζητημάτων
### Μελέτη βιβλιογραφίας

* Η μελέτη προηγούμενων ερευνών αποκαλύπτει "κενά" στη γνώση.
* Όχι απλώς συλλογή πηγών, αλλά συστηματική αναδιοργάνωση της βιβλιογραφίας
  
# Διευκρίνιση του ερευνητικού θέματος

## Γενικά

> **Ορισμός**
> 
> Η διευκρίνιση της αρχικής διατύπωσης διασφαλίζει τη μεταφορά από ένα γενικό
> πλαίσιο σε ένα συγκεκριμένο πρόβλημα.
   

## Χαρακτηριστικά "καλού" θέματος

\

Ένα καλό ερευνητικό θέμα πρέπει να:

* Είναι **ενδιαφέρον**.
* Διασφαλίζει τη **δυνατότητα έρευνας**.
* Είναι **σημαντικό**.
* Είναι **ηθικό**.
* Είναι **διαχειρίσιμο**.


# Διατύπωση του θέματος

## Γενικά

\

> **Ορισμός**
> 
> _Μία σύντομη και ακριβής περιγραφή του αντικειμένου της μελέτης, ώστε να μπορούν
> να στοιχειοθετηθούν τα επόμενα βήματα._

## Ποσοτική έρευνα

\

Σε μία ποσοτική έρευνα η διατύπωση συνήθως περιλαμβάνει τις μεταβλητές, τη σχέση
μεταξύ τους και τους συμμετέχοντες.

\

> **Παράδειγμα**
> 
> _Το θέμα που θα διερευνηθεί είναι η επίδραση των καρτών με ερωτήσεις μαθηματικών
> στην ακρίβεια της μέτρησης κατά τη διάρκεια του παιχνιδιού προσποίησης στο
> μανάβικο στα παιδιά του νηπιαγωγείου_.

## Ποιοτική έρευνα

Στην ποιοτική έρευνα έχουμε:

* Γενική διατύπωση
* Το θέμα εξειδικεύεται σταδιακά

> **Παράδειγμα**
> 
> _Σκοπός της μελέτης είναι να περιγράψει τη φύση της ενασχόλησης των παιδιών με τα
> μαθηματικά. Στόχος είναι να συγκεντρωθούν λεπτομέρειες σχετικά με τους τρόπους με
> τους οποίους τα παιδιά εισάγονται στα μαθηματικά και διατηρούν το ενδιαφέρον τους
> για αυτά_.

# Διατύπωση ερευνητικών ερωτημάτων

## Γενικά

* Ακριβής περιγραφή των των ζητημάτων που θα απαντηθούν από τη μελέτη.
* Επιβεβαίωση για τη δυνατότητα ολοκλήρωσης της μελέτης.

## Ποσοτική έρευνα

* Περιγραφή σχέσων μεταξύ μεταβλητών.
* Ποσοτικοποίηση των σχέσων αυτών.

> **Παράδειγμα**
> 
> _Η ακρίβεια της μέτρησης είναι μεγαλύτερη κατά τη διάρκεια των συνεδριών με
> κάρτες ερωτήσεων μαθηματικών συζητήσεων σε σύγκριση με τις συνεδρίες χωρίς
> αυτές;_

## Ποιοτική έρευνα

* Συνήθως ένα βασικό ερώτημα
* Μικρός αριθμός σχετικών (διευκρινιστικών) υπο-ερωτημάτων.

> **Παράδειγμα**
> 
> _Ποιες στρατηγικές χρησιμοποιούν τα παιδιά για να ασχοληθούν με τη μάθηση των
> μαθηματικών; Πώς αυτές οι στρατηγικές διατηρούν τη συμμετοχή των μαθητών στη
> μάθηση των μαθηματικών; Πώς η ενασχόληση με το περιεχόμενο των μαθηματικών
> επηρεάζει τη στάση των μαθητών απέναντι στα μαθημα;_

# Διατύπωση υποθέσεων

## Γενικά

> **Ορισμός**
> 
> _Η στοιχειοθετημένη πρόβλεψη του/της ερευνητή/τριας για το αποτέλεσμα της
> μελέτης και τις απαντήσεις στα ερευνητικά ερωτήματα._

## Ποσοτική έρευνα

* Αναπόσπαστο κομμάτι της ποσοτικής έρευνας.
* Συνήθως στηρίζονται σε κάποια επιστημονική θεωρία ή στα ευρήματα σχετικής
  βιβλιογραφίας.
  
## Χαρακτηριστικά "καλής" υπόθεσης

Μια καλή ερευνητική υπόθεση:

* Πρέπει να στηρίζεται σε μία στέρεη λογική και να συνάδει με τις επικρατούσες
  θεωρίες και τα αποτελέσματα προηγούμενων μελετών.
* Πρέπει να παρέχει μία λογική εξήγηση για το προβλεπόμενο αποτέλεσμα.
* Περιγράφει συνοπτικά και με σαφήνεια την αναμενόμενη σχέση ή διαφορά μεταξύ
  των μεταβλητών
* Μπορεί να ελεγχθεί μέσα σε λογικά χρονικά πλαίσια.

## Ποσοτική έρευνα

\


> **Μη-κατευθυντικές ερευνητικές υποθέσεις**
>
> _Υπάρχει μία σχέση ή διαφορά μεταξύ των μεταβλητών χωρίς να μας ενδιαφέρει η
> κατεύθυνσή της, π.χ. υπάρχει σχέση μεταξύ μίας παρέμβασης και της επίδοσης των
> μαθητών._
  
## Ποσοτική έρευνα

\

> **Κατευθυντικές ερευνητικές υποθέσεις**
>
> _Υπάρχει μία σχέση ή διαφορά μεταξύ των μεταβλητών με συγκεκριμένη κατεύθυνση,
> π.χ. η παρέμβαση βελτιώνει την επίδοση των μαθητών._

\

> **Μηδενική υπόθεση (null hypothesis)**
>
> _Προβλέπει ότι δεν υπάρχει καμία σχέση μεταξύ των μεταβλητών._

## Ποιοτική έρευνα

* Συνήθως δεν διατυπώνονται υποθέσεις
* Πολύ πιθανό να διατυπωθούν νέες υποθέσεις κατά τη διεξαγωγή της μελέτης

# Ανακεφαλαίωση

## Προσδιορισμός ερευνητικού θέματος

Για τον προσδιορισμό του ερευνητικού θέματος ακολουθούνται τα βήματα:

1. Γενική διατύπωση του ερευνητικού θέματος.
2. Διευκρίνιση του επιστημονικού θέματος.
3. Διατύπωση του ερευνητικού θέματος.
4. Διατύπωση ερευνητικών ερωτημάτων.
5. Διατύπωση ερευνητικών υποθέσεων.

## Ανακεφαλαίωση

* Η εκπαιδευτική έρευνα ακολουθεί συγκεκριμένα βήματα, με πρώτο τον ορισμό του
  ερευνητικού θέματος.
* Οι πηγές για ερευνητικά θέματα περιλαμβάνουν τη θεωρία, την πρακτική εμπειρία
  και τη βιβλιογραφία.
* Είναι κρίσιμο να περιορίσουμε ένα ευρύ θέμα σε ένα διαχειρίσιμο και εστιασμένο
  ερευνητικό ερώτημα.

## Ανακεφαλαίωση

* Ένα καλό ερευνητικό θέμα είναι ενδιαφέρον, ερευνήσιμο, σημαντικό και
  διαχειρίσιμο.
* Η υπόθεση είναι μια ελέγξιμη πρόβλεψη για το αποτέλεσμα της έρευνας, βασισμένη
  σε λογικά θεμέλια.
* Οι υποθέσεις διακρίνονται σε κατευθυντικές, μη-κατευθυντικές και μηδενικές.

## Παραδείγματα

* [ Μελέτη 1 ]( https://ejournals.epublishing.ekt.gr/index.php/hjre/article/view/24657/21182 )
* [ Μελέτη 2 ]( https://ejournals.epublishing.ekt.gr/index.php/hjre/article/view/19473/17390 )
* [ Μελέτη 3 ]( https://ejournals.epublishing.ekt.gr/index.php/omep/article/view/19570/19203 )
* [ Μελέτη 4 ]( https://ejournals.epublishing.ekt.gr/index.php/hjre/article/view/20808/18736 )
* [ Μελέτη 5 ]( https://ejournals.epublishing.ekt.gr/index.php/hjre/article/view/14232/14223 )
* [ Μελέτη 6 ]( https://ejournals.epublishing.ekt.gr/index.php/hjre/article/view/26026/21726 )

# Ευχαριστώ
